#CONFIGURATION

PATTERN_1_WIDGET = "EMAIL"
PATTERN_2_WIDGET = "WEATHER"
PATTERN_3_WIDGET = "NEWS"
PATTERN_4_WIDGET = "CLOSE-BACK"

#EMAIL WIDGET PREFERENCES

EMAIL_USERNAME = "drviruz94@gmail.com"
EMAIL_PWD = "94revenge"

NEWS_URL = 'https://www.thestar.com.my/rss/news/nation/'

#FACE_RECOGNITION

USER_NAME = "Darshan"
USER_TRAINED_XML = 'training.xml'
